dist:
  name: otelcol-custom
  description: Custom OTel Collector (contrib components)
  output_path: ./otelcol-custom
  version: 0.1.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.144.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.144.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.144.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.144.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.144.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.144.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.144.0
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.144.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckv2extension v0.144.0
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.144.0
